@startuml usercase
left to right direction

actor 用户 as User
actor 管理员 as Admin

rectangle "系统" {
  rectangle "客户端功能" {
    User --> (任务管理)
    (任务管理) ..> (创建任务) : include
    (任务管理) ..> (编辑任务) : include
    (任务管理) ..> (删除任务) : include

    (创建任务) <.. (优先级设置) : extend
    (创建任务) <.. (自动时间管理) : extend
    (编辑任务) <.. (优先级设置) : extend
    (编辑任务) <.. (自动时间管理) : extend

    User --> (使用番茄钟)
    User --> (查看调度结果)
    User --> (调度算法)
    (调度算法) ..> (本地调度) : include

  }

  rectangle "服务端功能" {
    Admin --> (AI 调度)
    (AI 调度) ..> (维护模型) : include
    (AI 调度) ..> (分析数据) : include
    Admin --> (监控服务端性能)
  }

}

' 注释与关系
note top of Admin
  服务端功能为可选模块
  仅在启用时管理员需参与

end note
@enduml