app:
  name: 任务调度系统
  debug: true
  host: 127.0.0.1
  port: 5000
frontend:
  host: 127.0.0.1
  port: 5173
database:
  path: api/data/tasks.db
  backup_path: api/data/backup
scheduler:
  default_algorithm: FCFS
  time_slice: 25
  task_density: medium
  daily_task_limit: 480
  enabled: true
  algorithm: round-robin
  customType: file
  customCode: ''
  densityPreference: none
  dailyTaskLimit: 6
  completionPreference: early
  sliceDuration: 25
  syncWithPomodoro: false
pomodoro:
  default_focus_time: 25
  default_rest_time: 5
  long_rest_time: 15
  long_rest_interval: 4
sync:
  timeout: 300
  qrcode_size: 200
  max_retry: 3
remote:
  cloudflared_path: utils/Cloudflared/cloudflared-windows-386.exe
  tunnel_wait_time: 6
  temp_file_suffix: .txt
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: logs/app.log
  max_size: 10485760
  backup_count: 5
priority:
  totalPriority: 5100
  intervalCount: 4
  intervals:
  - name: 高优先级
    min: 0
    max: 1700
  - name: 中优先级
    min: 1700
    max: 3400
  - name: 低优先级
    min: 3400
    max: 5100
  - name: 区间4
    min: 3825
    max: 5100
  priorityStep: 51
